# https://symfony.com/doc/current/security.html
security:
    encoders:
      FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
          pattern:  ^/api/v1/login
          stateless: true
          anonymous: true
          form_login:
            check_path:               /api/v1/login
            username_parameter:       _username
            password_parameter:       _password
            success_handler:          lexik_jwt_authentication.handler.authentication_success
            failure_handler:          lexik_jwt_authentication.handler.authentication_failure
            require_previous_session: false

        api:
          pattern:   ^/api/v1
          provider:  fos_userbundle
          anonymous: true
          stateless: true
          lexik_jwt:
            authorization_header:
              enabled: true
              prefix:  Bearer
            query_parameter:
              enabled: true
              name:    bearer
            throw_exceptions:        false
            create_entry_point:      true

    access_control:
        - { path: ^/api/v1/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/doc, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/, role: ROLE_USER }
